title: Grizwold's Blog
description: "-- hack your way through the day --"
author:
  name: "Grizwold"
  email: "tomekbielaszewski@gmail.com"
  url: "https://tomekbielaszewski.github.io/"

tag_page_layout: tag_page
tag_page_dir: tag
tag_page_data:
  sitemap: false
tag_permalink_style: pretty

google_analytics: UA-159875271-1

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 5
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

# Custom variables
owner : "Grizwold"
year : "2020"
